# Generated by Django 2.0 on 2018-11-23 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0006_auto_20181122_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='admin',
        ),
    ]
