# Generated by Django 2.0 on 2018-11-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0009_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
