# Generated by Django 2.0 on 2018-11-24 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0010_auto_20181123_1129'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='neighborhood',
            name='neighborhood_location',
        ),
    ]
