# Generated by Django 2.0 on 2018-11-24 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0011_remove_neighborhood_neighborhood_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
