# Generated by Django 2.0 on 2018-11-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hood', '0012_userprofile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='business_location',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
